/*
* Copyright (C) 2010 Jennifer Harlow
*
*/

/*! \file
\brief MappedFobj100D definitions.
*/


#include "mappedFobj100D.hpp"

using namespace subpavings;

cxsc::interval MappedFobj100D::operator()(const cxsc::ivector& ivec) const
{
	return this->operator()(
	ivec[1],
	ivec[2],
	ivec[3],
	ivec[4],
	ivec[5],
	ivec[6],
	ivec[7],
	ivec[8],
	ivec[9],
	ivec[10],
	ivec[11],
	ivec[12],
	ivec[13],
	ivec[14],
	ivec[15],
	ivec[16],
	ivec[17],
	ivec[18],
	ivec[19],
	ivec[20],
	ivec[21],
	ivec[22],
	ivec[23],
	ivec[24],
	ivec[25],
	ivec[26],
	ivec[27],
	ivec[28],
	ivec[29],
	ivec[30],
	ivec[31],
	ivec[32],
	ivec[33],
	ivec[34],
	ivec[35],
	ivec[36],
	ivec[37],
	ivec[38],
	ivec[39],
	ivec[40],
	ivec[41],
	ivec[42],
	ivec[43],
	ivec[44],
	ivec[45],
	ivec[46],
	ivec[47],
	ivec[48],
	ivec[49],
	ivec[50],
	ivec[51],
	ivec[52],
	ivec[53],
	ivec[54],
	ivec[55],
	ivec[56],
	ivec[57],
	ivec[58],
	ivec[59],
	ivec[60],
	ivec[61],
	ivec[62],
	ivec[63],
	ivec[64],
	ivec[65],
	ivec[66],
	ivec[67],
	ivec[68],
	ivec[69],
	ivec[70],
	ivec[71],
	ivec[72],
	ivec[73],
	ivec[74],
	ivec[75],
	ivec[76],
	ivec[77],
	ivec[78],
	ivec[79],
	ivec[80],
	ivec[81],
	ivec[82],
	ivec[83],
	ivec[84],
	ivec[85],
	ivec[86],
	ivec[87],
	ivec[88],
	ivec[89],
	ivec[90],
	ivec[91],
	ivec[92],
	ivec[93],
	ivec[94],
	ivec[95],
	ivec[96],
	ivec[97],
	ivec[98],
	ivec[99],
	ivec[100]
	);
}

cxsc::real MappedFobj100D::operator()(const cxsc::rvector& rv) const
{
	return this->operator()(
	rv[1],
	rv[2],
	rv[3],
	rv[4],
	rv[5],
	rv[6],
	rv[7],
	rv[8],
	rv[9],
	rv[10],
	rv[11],
	rv[12],
	rv[13],
	rv[14],
	rv[15],
	rv[16],
	rv[17],
	rv[18],
	rv[19],
	rv[20],
	rv[21],
	rv[22],
	rv[23],
	rv[24],
	rv[25],
	rv[26],
	rv[27],
	rv[28],
	rv[29],
	rv[30],
	rv[31],
	rv[32],
	rv[33],
	rv[34],
	rv[35],
	rv[36],
	rv[37],
	rv[38],
	rv[39],
	rv[40],
	rv[41],
	rv[42],
	rv[43],
	rv[44],
	rv[45],
	rv[46],
	rv[47],
	rv[48],
	rv[49],
	rv[50],
	rv[51],
	rv[52],
	rv[53],
	rv[54],
	rv[55],
	rv[56],
	rv[57],
	rv[58],
	rv[59],
	rv[60],
	rv[61],
	rv[62],
	rv[63],
	rv[64],
	rv[65],
	rv[66],
	rv[67],
	rv[68],
	rv[69],
	rv[70],
	rv[71],
	rv[72],
	rv[73],
	rv[74],
	rv[75],
	rv[76],
	rv[77],
	rv[78],
	rv[79],
	rv[80],
	rv[81],
	rv[82],
	rv[83],
	rv[84],
	rv[85],
	rv[86],
	rv[87],
	rv[88],
	rv[89],
	rv[90],
	rv[91],
	rv[92],
	rv[93],
	rv[94],
	rv[95],
	rv[96],
	rv[97],
	rv[98],
	rv[99],
	rv[100]
	);
}

cxsc::real MappedFobj100D::imageMid(const cxsc::ivector& ivec) const
{
	return this->operator()(
	cxsc::mid(ivec[1]),
	cxsc::mid(ivec[2]),
	cxsc::mid(ivec[3]),
	cxsc::mid(ivec[4]),
	cxsc::mid(ivec[5]),
	cxsc::mid(ivec[6]),
	cxsc::mid(ivec[7]),
	cxsc::mid(ivec[8]),
	cxsc::mid(ivec[9]),
	cxsc::mid(ivec[10]),
	cxsc::mid(ivec[11]),
	cxsc::mid(ivec[12]),
	cxsc::mid(ivec[13]),
	cxsc::mid(ivec[14]),
	cxsc::mid(ivec[15]),
	cxsc::mid(ivec[16]),
	cxsc::mid(ivec[17]),
	cxsc::mid(ivec[18]),
	cxsc::mid(ivec[19]),
	cxsc::mid(ivec[20]),
	cxsc::mid(ivec[21]),
	cxsc::mid(ivec[22]),
	cxsc::mid(ivec[23]),
	cxsc::mid(ivec[24]),
	cxsc::mid(ivec[25]),
	cxsc::mid(ivec[26]),
	cxsc::mid(ivec[27]),
	cxsc::mid(ivec[28]),
	cxsc::mid(ivec[29]),
	cxsc::mid(ivec[30]),
	cxsc::mid(ivec[31]),
	cxsc::mid(ivec[32]),
	cxsc::mid(ivec[33]),
	cxsc::mid(ivec[34]),
	cxsc::mid(ivec[35]),
	cxsc::mid(ivec[36]),
	cxsc::mid(ivec[37]),
	cxsc::mid(ivec[38]),
	cxsc::mid(ivec[39]),
	cxsc::mid(ivec[40]),
	cxsc::mid(ivec[41]),
	cxsc::mid(ivec[42]),
	cxsc::mid(ivec[43]),
	cxsc::mid(ivec[44]),
	cxsc::mid(ivec[45]),
	cxsc::mid(ivec[46]),
	cxsc::mid(ivec[47]),
	cxsc::mid(ivec[48]),
	cxsc::mid(ivec[49]),
	cxsc::mid(ivec[50]),
	cxsc::mid(ivec[51]),
	cxsc::mid(ivec[52]),
	cxsc::mid(ivec[53]),
	cxsc::mid(ivec[54]),
	cxsc::mid(ivec[55]),
	cxsc::mid(ivec[56]),
	cxsc::mid(ivec[57]),
	cxsc::mid(ivec[58]),
	cxsc::mid(ivec[59]),
	cxsc::mid(ivec[60]),
	cxsc::mid(ivec[61]),
	cxsc::mid(ivec[62]),
	cxsc::mid(ivec[63]),
	cxsc::mid(ivec[64]),
	cxsc::mid(ivec[65]),
	cxsc::mid(ivec[66]),
	cxsc::mid(ivec[67]),
	cxsc::mid(ivec[68]),
	cxsc::mid(ivec[69]),
	cxsc::mid(ivec[70]),
	cxsc::mid(ivec[71]),
	cxsc::mid(ivec[72]),
	cxsc::mid(ivec[73]),
	cxsc::mid(ivec[74]),
	cxsc::mid(ivec[75]),
	cxsc::mid(ivec[76]),
	cxsc::mid(ivec[77]),
	cxsc::mid(ivec[78]),
	cxsc::mid(ivec[79]),
	cxsc::mid(ivec[80]),
	cxsc::mid(ivec[81]),
	cxsc::mid(ivec[82]),
	cxsc::mid(ivec[83]),
	cxsc::mid(ivec[84]),
	cxsc::mid(ivec[85]),
	cxsc::mid(ivec[86]),
	cxsc::mid(ivec[87]),
	cxsc::mid(ivec[88]),
	cxsc::mid(ivec[89]),
	cxsc::mid(ivec[90]),
	cxsc::mid(ivec[91]),
	cxsc::mid(ivec[92]),
	cxsc::mid(ivec[93]),
	cxsc::mid(ivec[94]),
	cxsc::mid(ivec[95]),
	cxsc::mid(ivec[96]),
	cxsc::mid(ivec[97]),
	cxsc::mid(ivec[98]),
	cxsc::mid(ivec[99]),
	cxsc::mid(ivec[100])
	);
}

cxsc::real MappedFobj100D::imageMid(
	const cxsc::interval& ival1,
	const cxsc::interval& ival2,
	const cxsc::interval& ival3,
	const cxsc::interval& ival4,
	const cxsc::interval& ival5,
	const cxsc::interval& ival6,
	const cxsc::interval& ival7,
	const cxsc::interval& ival8,
	const cxsc::interval& ival9,
	const cxsc::interval& ival10,
	const cxsc::interval& ival11,
	const cxsc::interval& ival12,
	const cxsc::interval& ival13,
	const cxsc::interval& ival14,
	const cxsc::interval& ival15,
	const cxsc::interval& ival16,
	const cxsc::interval& ival17,
	const cxsc::interval& ival18,
	const cxsc::interval& ival19,
	const cxsc::interval& ival20,
	const cxsc::interval& ival21,
	const cxsc::interval& ival22,
	const cxsc::interval& ival23,
	const cxsc::interval& ival24,
	const cxsc::interval& ival25,
	const cxsc::interval& ival26,
	const cxsc::interval& ival27,
	const cxsc::interval& ival28,
	const cxsc::interval& ival29,
	const cxsc::interval& ival30,
	const cxsc::interval& ival31,
	const cxsc::interval& ival32,
	const cxsc::interval& ival33,
	const cxsc::interval& ival34,
	const cxsc::interval& ival35,
	const cxsc::interval& ival36,
	const cxsc::interval& ival37,
	const cxsc::interval& ival38,
	const cxsc::interval& ival39,
	const cxsc::interval& ival40,
	const cxsc::interval& ival41,
	const cxsc::interval& ival42,
	const cxsc::interval& ival43,
	const cxsc::interval& ival44,
	const cxsc::interval& ival45,
	const cxsc::interval& ival46,
	const cxsc::interval& ival47,
	const cxsc::interval& ival48,
	const cxsc::interval& ival49,
	const cxsc::interval& ival50,
	const cxsc::interval& ival51,
	const cxsc::interval& ival52,
	const cxsc::interval& ival53,
	const cxsc::interval& ival54,
	const cxsc::interval& ival55,
	const cxsc::interval& ival56,
	const cxsc::interval& ival57,
	const cxsc::interval& ival58,
	const cxsc::interval& ival59,
	const cxsc::interval& ival60,
	const cxsc::interval& ival61,
	const cxsc::interval& ival62,
	const cxsc::interval& ival63,
	const cxsc::interval& ival64,
	const cxsc::interval& ival65,
	const cxsc::interval& ival66,
	const cxsc::interval& ival67,
	const cxsc::interval& ival68,
	const cxsc::interval& ival69,
	const cxsc::interval& ival70,
	const cxsc::interval& ival71,
	const cxsc::interval& ival72,
	const cxsc::interval& ival73,
	const cxsc::interval& ival74,
	const cxsc::interval& ival75,
	const cxsc::interval& ival76,
	const cxsc::interval& ival77,
	const cxsc::interval& ival78,
	const cxsc::interval& ival79,
	const cxsc::interval& ival80,
	const cxsc::interval& ival81,
	const cxsc::interval& ival82,
	const cxsc::interval& ival83,
	const cxsc::interval& ival84,
	const cxsc::interval& ival85,
	const cxsc::interval& ival86,
	const cxsc::interval& ival87,
	const cxsc::interval& ival88,
	const cxsc::interval& ival89,
	const cxsc::interval& ival90,
	const cxsc::interval& ival91,
	const cxsc::interval& ival92,
	const cxsc::interval& ival93,
	const cxsc::interval& ival94,
	const cxsc::interval& ival95,
	const cxsc::interval& ival96,
	const cxsc::interval& ival97,
	const cxsc::interval& ival98,
	const cxsc::interval& ival99,
	const cxsc::interval& ival100) const
{
	return this->operator()(
		cxsc::mid(ival1),
		cxsc::mid(ival2),
		cxsc::mid(ival3),
		cxsc::mid(ival4),
		cxsc::mid(ival5),
		cxsc::mid(ival6),
		cxsc::mid(ival7),
		cxsc::mid(ival8),
		cxsc::mid(ival9),
		cxsc::mid(ival10),
		cxsc::mid(ival11),
		cxsc::mid(ival12),
		cxsc::mid(ival13),
		cxsc::mid(ival14),
		cxsc::mid(ival15),
		cxsc::mid(ival16),
		cxsc::mid(ival17),
		cxsc::mid(ival18),
		cxsc::mid(ival19),
		cxsc::mid(ival20),
		cxsc::mid(ival21),
		cxsc::mid(ival22),
		cxsc::mid(ival23),
		cxsc::mid(ival24),
		cxsc::mid(ival25),
		cxsc::mid(ival26),
		cxsc::mid(ival27),
		cxsc::mid(ival28),
		cxsc::mid(ival29),
		cxsc::mid(ival30),
		cxsc::mid(ival31),
		cxsc::mid(ival32),
		cxsc::mid(ival33),
		cxsc::mid(ival34),
		cxsc::mid(ival35),
		cxsc::mid(ival36),
		cxsc::mid(ival37),
		cxsc::mid(ival38),
		cxsc::mid(ival39),
		cxsc::mid(ival40),
		cxsc::mid(ival41),
		cxsc::mid(ival42),
		cxsc::mid(ival43),
		cxsc::mid(ival44),
		cxsc::mid(ival45),
		cxsc::mid(ival46),
		cxsc::mid(ival47),
		cxsc::mid(ival48),
		cxsc::mid(ival49),
		cxsc::mid(ival50),
		cxsc::mid(ival51),
		cxsc::mid(ival52),
		cxsc::mid(ival53),
		cxsc::mid(ival54),
		cxsc::mid(ival55),
		cxsc::mid(ival56),
		cxsc::mid(ival57),
		cxsc::mid(ival58),
		cxsc::mid(ival59),
		cxsc::mid(ival60),
		cxsc::mid(ival61),
		cxsc::mid(ival62),
		cxsc::mid(ival63),
		cxsc::mid(ival64),
		cxsc::mid(ival65),
		cxsc::mid(ival66),
		cxsc::mid(ival67),
		cxsc::mid(ival68),
		cxsc::mid(ival69),
		cxsc::mid(ival70),
		cxsc::mid(ival71),
		cxsc::mid(ival72),
		cxsc::mid(ival73),
		cxsc::mid(ival74),
		cxsc::mid(ival75),
		cxsc::mid(ival76),
		cxsc::mid(ival77),
		cxsc::mid(ival78),
		cxsc::mid(ival79),
		cxsc::mid(ival80),
		cxsc::mid(ival81),
		cxsc::mid(ival82),
		cxsc::mid(ival83),
		cxsc::mid(ival84),
		cxsc::mid(ival85),
		cxsc::mid(ival86),
		cxsc::mid(ival87),
		cxsc::mid(ival88),
		cxsc::mid(ival89),
		cxsc::mid(ival90),
		cxsc::mid(ival91),
		cxsc::mid(ival92),
		cxsc::mid(ival93),
		cxsc::mid(ival94),
		cxsc::mid(ival95),
		cxsc::mid(ival96),
		cxsc::mid(ival97),
		cxsc::mid(ival98),
		cxsc::mid(ival99),
		cxsc::mid(ival100)
		);
	/*int ivL = Lb(iv);
	int ivU = Ub(iv);
	rvector rv(ivU - ivL +1 );
	for (int i = ivL; i<=ivU; i++) {
		rv[i] = mid(iv[i]);
	}
	return this->operator()(rv);
	*/
}
