/*! \file RosenFobj100D.hpp
\brief Declarations for MappedSPnode 1-d example function object class
*/

#ifndef __RosenFOBJ100D_HPP__
#define __RosenFOBJ100D_HPP__


#include "mappedFobj100D.hpp"


class RosenFobj100D : public subpavings::MappedFobj100D {

    public:

        //! no argument constructor
        RosenFobj100D() {};

        //! declare function for interval image of a box
        virtual cxsc::interval operator()(const cxsc::interval& ival1,
const cxsc::interval& ival2,
const cxsc::interval& ival3,
const cxsc::interval& ival4,
const cxsc::interval& ival5,
const cxsc::interval& ival6,
const cxsc::interval& ival7,
const cxsc::interval& ival8,
const cxsc::interval& ival9,
const cxsc::interval& ival10,
const cxsc::interval& ival11,
const cxsc::interval& ival12,
const cxsc::interval& ival13,
const cxsc::interval& ival14,
const cxsc::interval& ival15,
const cxsc::interval& ival16,
const cxsc::interval& ival17,
const cxsc::interval& ival18,
const cxsc::interval& ival19,
const cxsc::interval& ival20,
const cxsc::interval& ival21,
const cxsc::interval& ival22,
const cxsc::interval& ival23,
const cxsc::interval& ival24,
const cxsc::interval& ival25,
const cxsc::interval& ival26,
const cxsc::interval& ival27,
const cxsc::interval& ival28,
const cxsc::interval& ival29,
const cxsc::interval& ival30,
const cxsc::interval& ival31,
const cxsc::interval& ival32,
const cxsc::interval& ival33,
const cxsc::interval& ival34,
const cxsc::interval& ival35,
const cxsc::interval& ival36,
const cxsc::interval& ival37,
const cxsc::interval& ival38,
const cxsc::interval& ival39,
const cxsc::interval& ival40,
const cxsc::interval& ival41,
const cxsc::interval& ival42,
const cxsc::interval& ival43,
const cxsc::interval& ival44,
const cxsc::interval& ival45,
const cxsc::interval& ival46,
const cxsc::interval& ival47,
const cxsc::interval& ival48,
const cxsc::interval& ival49,
const cxsc::interval& ival50,
const cxsc::interval& ival51,
const cxsc::interval& ival52,
const cxsc::interval& ival53,
const cxsc::interval& ival54,
const cxsc::interval& ival55,
const cxsc::interval& ival56,
const cxsc::interval& ival57,
const cxsc::interval& ival58,
const cxsc::interval& ival59,
const cxsc::interval& ival60,
const cxsc::interval& ival61,
const cxsc::interval& ival62,
const cxsc::interval& ival63,
const cxsc::interval& ival64,
const cxsc::interval& ival65,
const cxsc::interval& ival66,
const cxsc::interval& ival67,
const cxsc::interval& ival68,
const cxsc::interval& ival69,
const cxsc::interval& ival70,
const cxsc::interval& ival71,
const cxsc::interval& ival72,
const cxsc::interval& ival73,
const cxsc::interval& ival74,
const cxsc::interval& ival75,
const cxsc::interval& ival76,
const cxsc::interval& ival77,
const cxsc::interval& ival78,
const cxsc::interval& ival79,
const cxsc::interval& ival80,
const cxsc::interval& ival81,
const cxsc::interval& ival82,
const cxsc::interval& ival83,
const cxsc::interval& ival84,
const cxsc::interval& ival85,
const cxsc::interval& ival86,
const cxsc::interval& ival87,
const cxsc::interval& ival88,
const cxsc::interval& ival89,
const cxsc::interval& ival90,
const cxsc::interval& ival91,
const cxsc::interval& ival92,
const cxsc::interval& ival93,
const cxsc::interval& ival94,
const cxsc::interval& ival95,
const cxsc::interval& ival96,
const cxsc::interval& ival97,
const cxsc::interval& ival98,
const cxsc::interval& ival99,
const cxsc::interval& ival100) const;

        //! declare function for real image of reals
        virtual cxsc::real operator()(const cxsc::real& r1,
const cxsc::real& r2,
const cxsc::real& r3,
const cxsc::real& r4,
const cxsc::real& r5,
const cxsc::real& r6,
const cxsc::real& r7,
const cxsc::real& r8,
const cxsc::real& r9,
const cxsc::real& r10,
const cxsc::real& r11,
const cxsc::real& r12,
const cxsc::real& r13,
const cxsc::real& r14,
const cxsc::real& r15,
const cxsc::real& r16,
const cxsc::real& r17,
const cxsc::real& r18,
const cxsc::real& r19,
const cxsc::real& r20,
const cxsc::real& r21,
const cxsc::real& r22,
const cxsc::real& r23,
const cxsc::real& r24,
const cxsc::real& r25,
const cxsc::real& r26,
const cxsc::real& r27,
const cxsc::real& r28,
const cxsc::real& r29,
const cxsc::real& r30,
const cxsc::real& r31,
const cxsc::real& r32,
const cxsc::real& r33,
const cxsc::real& r34,
const cxsc::real& r35,
const cxsc::real& r36,
const cxsc::real& r37,
const cxsc::real& r38,
const cxsc::real& r39,
const cxsc::real& r40,
const cxsc::real& r41,
const cxsc::real& r42,
const cxsc::real& r43,
const cxsc::real& r44,
const cxsc::real& r45,
const cxsc::real& r46,
const cxsc::real& r47,
const cxsc::real& r48,
const cxsc::real& r49,
const cxsc::real& r50,
const cxsc::real& r51,
const cxsc::real& r52,
const cxsc::real& r53,
const cxsc::real& r54,
const cxsc::real& r55,
const cxsc::real& r56,
const cxsc::real& r57,
const cxsc::real& r58,
const cxsc::real& r59,
const cxsc::real& r60,
const cxsc::real& r61,
const cxsc::real& r62,
const cxsc::real& r63,
const cxsc::real& r64,
const cxsc::real& r65,
const cxsc::real& r66,
const cxsc::real& r67,
const cxsc::real& r68,
const cxsc::real& r69,
const cxsc::real& r70,
const cxsc::real& r71,
const cxsc::real& r72,
const cxsc::real& r73,
const cxsc::real& r74,
const cxsc::real& r75,
const cxsc::real& r76,
const cxsc::real& r77,
const cxsc::real& r78,
const cxsc::real& r79,
const cxsc::real& r80,
const cxsc::real& r81,
const cxsc::real& r82,
const cxsc::real& r83,
const cxsc::real& r84,
const cxsc::real& r85,
const cxsc::real& r86,
const cxsc::real& r87,
const cxsc::real& r88,
const cxsc::real& r89,
const cxsc::real& r90,
const cxsc::real& r91,
const cxsc::real& r92,
const cxsc::real& r93,
const cxsc::real& r94,
const cxsc::real& r95,
const cxsc::real& r96,
const cxsc::real& r97,
const cxsc::real& r98,
const cxsc::real& r99,
const cxsc::real& r100
) const;

        // use base class for midImage

        //! Destructor
        ~RosenFobj100D(){}


};
#endif
