#/bin/bash

rm *.txt

SAMPLESIZE=100000
DIM=2 #rmb to change the function objects in the .cpp
NUMSIMULATIONS=1
TOLSIM=100 

MAXLOOPS=1000000;
SAMPLESNEEDED=10000
THINOUT=10
TOLLEAVES=0.1;
MINPOINTS=1

SEED=1;
NL=1; #hist1
MAXLEAF=500 #hist2


./MappedSPSamplingGaussian $SAMPLESIZE $DIM $NUMSIMULATIONS $TOLSIM $MAXLOOPS $SAMPLESNEEDED $THINOUT $TOLLEAVES $MINPOINTS $SEED $MAXLEAF $NL

#./MappedSPSamplingTest $SAMPLESIZE $DIM $NUMSIMULATIONS $TOLSIM $MAXLOOPS $SAMPLESNEEDED $THINOUT $TOLLEAVES $MINPOINTS $SEED $MAXLEAF

