#!/bin/bash
#Mortality of slash variety of pine seelings planted too high or two deep
#Consonni and Veronese (1955) from Table 1 of Green (1995)
#./BinomialPartition 1000000 10000000 0 1 2 100 88 100 95
#Mortality of longleaf variety of pine seelings planted too high or two deep
#./BinomialPartition 10000 10000 0 1 2 100 59 100 89 
#./BinomialPartition 250000 100000 0 1 4 100 59 100 89 100 88 100 95
#thisi is for the bi partition of Indian monsoon at 1976 into the following data:
#n_1 = 250000, y_1 = 1264 and n_2 = 250000, y_2 = 1542
################################################################3
#to statically compile do
#make clean
#make
#rm BinomialPartition
#g++ -static -g -O2  -L/home/raazesh/all/software/cxsc/cxsc-2-5-4/lib -L/home/raazesh/all/software/gsl/gsl-2.1/lib -o BinomialPartition BinomialPartition-BinomialPartition.o ../../targets/BinomialPartition-FBinomialPartition.o -lcxsc ../../../src/libmrs.a -lcxsc -lgsl -lgslcblas -lm
